server:
  port: 9094

spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: qthuy2609@gmail.com
    password: ${EMAIL_APPLICATION_PASS}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  kafka:
    bootstrap-servers:
      - broker:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "[spring.json.type.mapping]": order:com.qthuy2k1.notificationservice.dto.OrderPlaced,user:com.qthuy2k1.notificationservice.dto.UserCreated

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@eureka-server:8761/eureka
  instance:
    hostname: notification-service
    prefer-ip-address: true
