server:
  port: 8081

spring:
  application:
    name: user
  datasource:
    username: "postgres"
    password: "root"
    url: jdbc:postgresql://localhost:5433/users_db
  jpa:
    properties:
      hibernate:
        format_sql: "true"
    hibernate:
      ddl-auto: update
    show-sql: "true"
