server:
  port: 12345

spring:
  application:
    name: "user"
  datasource:
    username: "postgres"
    password: "root"
    url: jdbc:postgresql://localhost:5433/users_db
  jpa:
    properties:
      hibernate:
        format_sql: "true"
    hibernate:
      ddl-auto: update
    show-sql: "true"
  kafka:
    bootstrap-servers:
      - localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        "[spring.json.type.mapping]": user:com.qthuy2k1.user.event.UserCreated

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
  instance:
    hostname: localhost
