version: "3.8"

services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: qthuy2609@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - mynet
    restart: unless-stopped

  # User DB
  postgres-user:
    container_name: postgres-user
    image: postgres
    networks:
      - mynet
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: users_db
      PG_DATA: /data/postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-user:/data/postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d users_db'" ]
      interval: 10s
      timeout: 3s
      retries: 3

  # Product DB
  postgres-product:
    container_name: postgres-product
    image: postgres
    networks:
      - mynet
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: products_db
      PG_DATA: /data/postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres-product:/data/postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d products_db'" ]
      interval: 10s
      timeout: 3s
      retries: 3

  # Order DB
  postgres-order:
    container_name: postgres-order
    image: postgres
    networks:
      - mynet
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: orders_db
      PG_DATA: /data/postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres-order:/data/postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d orders_db'" ]
      interval: 10s
      timeout: 3s
      retries: 3

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    networks:
      - mynet
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    networks:
      - mynet
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: [ "CMD", "bash", "-c", "unset" , "JMX_PORT" ,";" ,"kafka-topics.sh","--zookeeper","zookeeper:2181","--list" ]
  #    healthcheck:
  #      test: [ "CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181" ]
  #      interval: 5s
  #      timeout: 10s
  #      retries: 5

  eureka-server:
    image: qthuy2k1/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - mynet
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  
  api-gateway:
    image: qthuy2k1/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - mynet
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: on-failure

  notification:
    image: qthuy2k1/notification:latest
    container_name: notification
    networks:
      - mynet
    depends_on:
      eureka-server:
        condition: service_started
      kafka:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  order:
    image: qthuy2k1/order:latest
    container_name: order
    networks:
      - mynet
    depends_on:
      eureka-server:
        condition: service_started
      postgres-order:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  product:
    image: qthuy2k1/product:latest
    container_name: product
    networks:
      - mynet
    depends_on:
      eureka-server:
        condition: service_started
      postgres-product:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  user:
    image: qthuy2k1/user:latest
    container_name: user
    networks:
      - mynet
    depends_on:
      eureka-server:
        condition: service_started
      postgres-user:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  mynet:
    driver: bridge

volumes:
  postgres-db:
  pgadmin:
  postgres-user:
  postgres-product:
  postgres-order: