eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@eureka-server:8761/eureka
  instance:
    preferIpAddress: true

app:
  api-prefix: /api/v1
  user-url: "lb://user-service"

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans