server:
  port: 0

spring:
  application:
    name: notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: qthuy2609@gmail.com
    password: ${EMAIL_APPLICATION_PASS}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  kafka:
    bootstrap-servers:
      - localhost:29092

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
  instance:
    hostname: localhost
