server:
  port: 0

spring:
  application:
    name: order
  datasource:
    username: "postgres"
    password: "root"
    url: jdbc:postgresql://postgres-order:5432/orders_db
  jpa:
    properties:
      hibernate:
        format_sql: "true"
    hibernate:
      ddl-auto: update
    show-sql: "true"
  kafka:
    bootstrap-servers:
      - kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        "[spring.json.type.mapping]": order:com.qthuy2k1.order.event.OrderPlaced

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@eureka-server:8761/eureka
  instance:
    hostname: order

management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: always
management.health.circuitbreakers.enabled: true

# Resilience4j Properties
resilience4j:
  circuitbreaker:
    instances:
      user:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  #Resilience4J Timeout Properties
  timelimiter.instances.user.timeout-duration: 3s
  #Resilience4J Retry Properties
  retry.instances.user.max-attempts: 3
  retry.instances.user.wait-duration: 5
