server:
  port: 9093

spring:
  application:
    name: payment-service
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: example
      database: payments_db
      port: 27017
      host: localhost


## Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
  #    enabled: false
  instance:
    hostname: localhost
    prefer-ip-address: true


management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always