spring:
  data:
    mongodb:
      host: mongo-payment
## Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@eureka-server:8761/eureka
  instance:
    hostname: payment-service
    prefer-ip-address: true

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
