server:
  port: 9091

spring:
  application:
    name: "user-service"
  datasource:
    username: "postgres"
    password: "root"
    url: jdbc:postgresql://localhost:5433/users_db
  jpa:
    properties:
      hibernate:
        format_sql: "true"
    hibernate:
      ddl-auto: update
    show-sql: "true"
  kafka:
    bootstrap-servers:
      - localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        "[spring.json.type.mapping]": user:com.qthuy2k1.userservice.event.UserCreated
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: REDIS
    redis:
      cache-null-values: false
      use-key-prefix: true
      key-prefix: user
      time-to-live: 600000
  jwt:
    signerKey: "iYcJS25OwsLDyqgCWgDQ/s7w4QqpU9A15MWniRM5Y0bj73JO/hlXksVLr3fnJt/y"
    valid-duration: 3600 # in second
    refreshable-duration: 36000
  jackson:
    serialization:
      INDENT_OUTPUT: true

## Eureka
eureka:
  client:
    #    enabled: false
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true


management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enable: true
    ratelimiters:
      enable: true

resilience4j:
  circuitbreaker:
    instances:
      inventoryService:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        registerHealthIndicator: true
  retry:
    instances:
      inventoryService:
        maxRetryAttempts: 5
        waitDuration: 5s