server:
  port: 9091

spring:
  datasource:
    url: jdbc:postgresql://postgres-user:5432/users_db
  kafka:
    bootstrap-servers:
      - broker:9092
  data:
    redis:
      host: redis

## Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}


management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
#management:
#  tracing:
#    exporter:
#      zipkin:
#        endpoint: http://zipkin:9411/api/v2/spans