apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongodb-payment
  name: mongodb-payment
spec:
  serviceName: mongodb-payment
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-payment
  template:
    metadata:
      labels:
        app: mongodb-payment
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example
          image: mongo
          name: mongodb-payment
          ports:
            - containerPort: 27017
          resources: { }
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-payment-claim0
      restartPolicy: Always
      volumes:
        - name: mongodb-payment-claim0
          persistentVolumeClaim:
            claimName: mongodb-payment-claim0
status: { }
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-payment
  name: mongodb-payment
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    app: mongodb-payment
status:
  loadBalancer: { }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mongodb-payment-claim0
  name: mongodb-payment-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: { }
