spring:
  datasource:
    url: jdbc:postgresql://postgres-order:5432/orders_db
  kafka:
    bootstrap-servers:
      - broker:9092


## Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@eureka-server:8761/eureka
  instance:
    hostname: order-service
    prefer-ip-address: true

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
