server:
  port: 19292

spring:
  application:
    name: product-service
  datasource:
    username: "postgres"
    password: "root"
    url: jdbc:postgresql://localhost:5434/products_db
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 4
        format_sql: "true"
    hibernate:
      ddl-auto: update
    show-sql: "true"
  graphql:
    path: /products/graphql
    graphiql:
      enabled: true
      path: /products/graphiql
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: REDIS
    redis:
      cache-null-values: false
      time-to-live: 600000

## Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
    enabled: false
  instance:
    hostname: localhost
    prefer-ip-address: true

management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: always
management.health.circuitbreakers.enabled: true


## Zipkin
management:
  tracing:
    sampling:
      probability: 1.0

# Resilience4j Properties
resilience4j:
  circuitbreaker:
    instances:
      user:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  #Resilience4J Timeout Properties
  timelimiter.instances.user.timeout-duration: 3s
  #Resilience4J Retry Properties
  retry.instances.user.max-attempts: 3
  retry.instances.user.wait-duration: 5


