server:
  port: 9092

spring:
  datasource:
    url: jdbc:postgresql://postgres-product:5432/products_db

## Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@eureka-server:8761/eureka
  instance:
    hostname: product-service
    prefer-ip-address: true