spring:
  application:
    name: "inventory-service"
  datasource:
    username: "postgres"
    password: "root"
    url: jdbc:postgresql://localhost:5436/inventories_db
  jpa:
    properties:
      hibernate:
        format_sql: "true"
    hibernate:
      ddl-auto: update
    show-sql: "true"
  kafka:
    bootstrap-servers:
      - localhost:29092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
## Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

server:
  port: 0

## Zipkin
management:
  tracing:
    sampling:
      probability: 1.0
