spring:
  application:
    name: "inventory-service"
  datasource:
    username: "postgres"
    password: "root"
    url: jdbc:postgresql://localhost:5436/inventories_db
  jpa:
    properties:
      hibernate:
        format_sql: "true"
    hibernate:
      ddl-auto: update
    show-sql: "true"

## Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

server:
  port: 0
