apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment-service
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  strategy: { }
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: qthuy2k1/payment-service:latest
          name: payment-service
          resources: { }
          imagePullPolicy: Always
      restartPolicy: Always
status: { }
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: payment-service
  name: payment-service
spec:
  ports:
    - port: 80
      targetPort: 9096
  selector:
    app: payment-service
status:
  loadBalancer: { }