apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  strategy: { }
  template:
    metadata:

      labels:
        app: user-service
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: qthuy2k1/user-service:latest
          name: user-service
          resources: { }
          imagePullPolicy: Always
      restartPolicy: Always
status: { }
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-service
  name: user-service
spec:
  ports:
    - port: 80
      targetPort: 9091
  selector:
    app: user-service
status:
  loadBalancer: { }